name: Deploy Storybook

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Clean Old Build
        run: rm -rf ./storybook-static

      - name: Build Storybook
        run: npm run build-storybook

      - name: Verify Storybook Build
        run: ls -R ./storybook-static

      - name: Add .nojekyll
        run: echo "" > ./storybook-static/.nojekyll

      - name: Ensure Storybook Entry Point
        run: cp ./storybook-static/index.html ./storybook-static/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: gh-pages
          force_orphan: true
